import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireAuth } from "../auth/middleware";
import { db, schema } from "../db";
import { eq, desc, sql, ilike, or } from "drizzle-orm";
import { recordAudit } from "../utils/audit";
import { NotFoundError } from "../utils/errors";

export async function kbRoutes(app: FastifyInstance) {
  // Search / list articles
  app.get("/", { preHandler: requireAuth }, async (req) => {
    const q = z.object({
      search: z.string().optional(),
      tag: z.string().optional(),
      systemId: z.string().uuid().optional(),
      page: z.coerce.number().default(1),
      limit: z.coerce.number().max(50).default(20),
    }).parse(req.query);

    const conditions = [eq(schema.kbArticles.published, true)];

    if (q.search) {
      conditions.push(
        or(
          ilike(schema.kbArticles.title, `%${q.search}%`),
          ilike(schema.kbArticles.content, `%${q.search}%`),
          ilike(schema.kbArticles.summary, `%${q.search}%`),
        )!,
      );
    }
    if (q.tag) {
      conditions.push(sql`${q.tag} = ANY(${schema.kbArticles.tags})`);
    }
    if (q.systemId) conditions.push(eq(schema.kbArticles.systemId, q.systemId));

    const whereClause = conditions.reduce((a, b) => sql`${a} AND ${b}`);

    const articles = await db
      .select({
        id: schema.kbArticles.id,
        title: schema.kbArticles.title,
        summary: schema.kbArticles.summary,
        tags: schema.kbArticles.tags,
        autoGenerated: schema.kbArticles.autoGenerated,
        viewCount: schema.kbArticles.viewCount,
        helpful: schema.kbArticles.helpful,
        createdAt: schema.kbArticles.createdAt,
        updatedAt: schema.kbArticles.updatedAt,
        system: { name: schema.systems.name, type: schema.systems.type },
        createdByUser: { displayName: schema.users.displayName },
      })
      .from(schema.kbArticles)
      .leftJoin(schema.systems, eq(schema.kbArticles.systemId, schema.systems.id))
      .leftJoin(schema.users, eq(schema.kbArticles.createdBy, schema.users.id))
      .where(whereClause)
      .orderBy(desc(schema.kbArticles.updatedAt))
      .limit(q.limit)
      .offset((q.page - 1) * q.limit);

    return articles;
  });

  // Get article
  app.get("/:id", { preHandler: requireAuth }, async (req) => {
    const { id } = req.params as { id: string };

    const [article] = await db
      .select()
      .from(schema.kbArticles)
      .where(eq(schema.kbArticles.id, id))
      .limit(1);

    if (!article) throw new NotFoundError("Artículo KB");

    // increment view count
    await db
      .update(schema.kbArticles)
      .set({ viewCount: sql`${schema.kbArticles.viewCount} + 1` })
      .where(eq(schema.kbArticles.id, id));

    const [system, createdByUser, sourceIncident] = await Promise.all([
      article.systemId
        ? db.select().from(schema.systems).where(eq(schema.systems.id, article.systemId)).limit(1)
        : Promise.resolve([]),
      article.createdBy
        ? db.select({ displayName: schema.users.displayName }).from(schema.users).where(eq(schema.users.id, article.createdBy)).limit(1)
        : Promise.resolve([]),
      article.sourceIncidentId
        ? db.select({ id: schema.incidents.id, title: schema.incidents.title }).from(schema.incidents).where(eq(schema.incidents.id, article.sourceIncidentId)).limit(1)
        : Promise.resolve([]),
    ]);

    return {
      ...article,
      system: (system as any)[0] ?? null,
      createdByUser: (createdByUser as any)[0] ?? null,
      sourceIncident: (sourceIncident as any)[0] ?? null,
    };
  });

  // Create article manually
  app.post("/", { preHandler: requireAuth }, async (req, reply) => {
    const body = z.object({
      title: z.string().min(3),
      content: z.string().min(10),
      summary: z.string().optional(),
      tags: z.array(z.string()).default([]),
      systemId: z.string().uuid().optional(),
      published: z.boolean().default(true),
    }).parse(req.body);

    const [article] = await db
      .insert(schema.kbArticles)
      .values({ ...body, createdBy: req.user.sub, updatedBy: req.user.sub })
      .returning();

    await recordAudit({
      userId: req.user.sub,
      action: "create",
      entityType: "kb_article",
      entityId: article.id,
      entityName: article.title,
      description: `${req.user.displayName} creó artículo KB: ${article.title}`,
      req,
    });

    return reply.status(201).send(article);
  });

  // Update article
  app.put("/:id", { preHandler: requireAuth }, async (req) => {
    const { id } = req.params as { id: string };
    const body = z.object({
      title: z.string().min(3).optional(),
      content: z.string().optional(),
      summary: z.string().optional(),
      tags: z.array(z.string()).optional(),
      published: z.boolean().optional(),
    }).parse(req.body);

    const [before] = await db.select().from(schema.kbArticles).where(eq(schema.kbArticles.id, id)).limit(1);
    if (!before) throw new NotFoundError("Artículo KB");

    const [updated] = await db
      .update(schema.kbArticles)
      .set({ ...body, updatedBy: req.user.sub, updatedAt: new Date() })
      .where(eq(schema.kbArticles.id, id))
      .returning();

    await recordAudit({
      userId: req.user.sub,
      action: "update",
      entityType: "kb_article",
      entityId: id,
      entityName: before.title,
      description: `${req.user.displayName} actualizó artículo KB: ${before.title}`,
      req,
    });

    return updated;
  });

  // Rate article
  app.post("/:id/rate", { preHandler: requireAuth }, async (req) => {
    const { id } = req.params as { id: string };
    const { helpful } = z.object({ helpful: z.boolean() }).parse(req.body);

    const [updated] = await db
      .update(schema.kbArticles)
      .set(
        helpful
          ? { helpful: sql`${schema.kbArticles.helpful} + 1` }
          : { notHelpful: sql`${schema.kbArticles.notHelpful} + 1` },
      )
      .where(eq(schema.kbArticles.id, id))
      .returning({ helpful: schema.kbArticles.helpful, notHelpful: schema.kbArticles.notHelpful });

    return updated;
  });
}
