export type Severity = "critica" | "alta" | "media" | "baja" | "info";
export type IncidentStatus = "abierta" | "en_progreso" | "pendiente" | "resuelta" | "cerrada";
export type UserRole = "admin" | "tecnico" | "readonly";
export type AutomationStatus = "pendiente" | "ejecutando" | "completada" | "fallida" | "cancelada";
export type SystemStatus = "ok" | "degradado" | "critico" | "desconocido";

export interface User {
  id: string;
  username: string;
  displayName: string;
  email: string;
  role: UserRole;
  avatar?: string;
  lastLogin?: string;
}

export interface AlertSummary {
  externalId: string;
  title: string;
  description?: string;
  severity: Severity;
  systemName: string;
  firedAt: string;
  metadata?: Record<string, unknown>;
}

export interface ConnectorResult {
  type: string;
  displayName: string;
  healthy: boolean;
  latencyMs?: number;
  error?: string;
}

export interface SystemStatusItem {
  externalId: string;
  name: string;
  type: string;
  status: SystemStatus;
  metrics?: { cpu?: number; memory?: number; disk?: number; uptime?: number };
  metadata?: Record<string, unknown>;
}

export interface DashboardSummary {
  alerts: {
    total: number;
    critical: number;
    high: number;
    topAlerts: AlertSummary[];
  };
  systems: {
    total: number;
    ok: number;
    degraded: number;
    critical: number;
    healthPercent: number;
  };
  incidents: { open: number; today: number };
  connectors: { total: number; healthy: number; list: ConnectorResult[] };
  demoMode: boolean;
}

export interface Incident {
  id: string;
  title: string;
  description?: string;
  severity: Severity;
  status: IncidentStatus;
  tags: string[];
  rootCause?: string;
  resolution?: string;
  impact?: string;
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
  closedAt?: string;
  assignedUser?: { id: string; displayName: string; avatar?: string };
  system?: { id: string; name: string; type: string };
  checklist?: ChecklistItem[];
  comments?: IncidentComment[];
  automationRuns?: AutomationRunSummary[];
  kbArticleId?: string;
}

export interface ChecklistItem {
  id: string;
  text: string;
  completed: boolean;
  completedAt?: string;
  order: number;
}

export interface IncidentComment {
  id: string;
  content: string;
  isSystemMessage: boolean;
  createdAt: string;
  author?: { id: string; displayName: string; avatar?: string };
}

export interface AutomationAction {
  id: string;
  name: string;
  description?: string;
  category: string;
  icon?: string;
  targetType: string;
  connectorType?: string;
  parameters: ActionParameter[];
  jobName: string;
  requiredRole: UserRole;
  dangerous: boolean;
  active: boolean;
}

export interface ActionParameter {
  name: string;
  type: "string" | "number" | "boolean" | "select";
  label: string;
  required?: boolean;
  default?: unknown;
  placeholder?: string;
  options?: string[];
}

export interface AutomationRun {
  id: string;
  status: AutomationStatus;
  output?: string;
  error?: string;
  parameters: Record<string, unknown>;
  startedAt?: string;
  finishedAt?: string;
  createdAt: string;
  action?: { id: string; name: string; category: string };
  triggeredBy?: { id: string; displayName: string };
  system?: { name: string };
}

export interface AutomationRunSummary {
  id: string;
  status: AutomationStatus;
  createdAt: string;
  finishedAt?: string;
  action?: { name: string; category: string };
  user?: { displayName: string };
}

export interface KbArticle {
  id: string;
  title: string;
  content: string;
  summary?: string;
  tags: string[];
  autoGenerated: boolean;
  published: boolean;
  viewCount: number;
  helpful: number;
  notHelpful: number;
  createdAt: string;
  updatedAt: string;
  system?: { name: string; type: string };
  createdByUser?: { displayName: string };
  sourceIncident?: { id: string; title: string };
}

export interface Notification {
  id: string;
  title: string;
  body: string;
  type: "info" | "warning" | "error" | "success";
  read: boolean;
  link?: string;
  entityType?: string;
  entityId?: string;
  createdAt: string;
}

export interface ScheduledJob {
  id: string;
  name: string;
  cronExpression: string;
  parameters: Record<string, unknown>;
  enabled: boolean;
  lastRun?: string;
  lastRunStatus?: string;
  nextRun?: string;
  createdAt: string;
  action: { id: string; name: string; category: string };
}

export interface SshCredential {
  id: string;
  name: string;
  host: string;
  port: number;
  username: string;
  description?: string;
  tags: string[];
  active: boolean;
  createdAt: string;
}

export interface MetricSnapshot {
  timestamp: string;
  value: number;
}

export interface MetricHistory {
  source: string;
  metricType: string;
  data: MetricSnapshot[];
  stats: { min: number; max: number; avg: number; latest: number };
}

export interface AuditEvent {
  id: string;
  action: string;
  entityType: string;
  entityId?: string;
  entityName?: string;
  description: string;
  changes?: { before?: unknown; after?: unknown };
  ipAddress?: string;
  createdAt: string;
  user?: { id: string; displayName: string; username: string; avatar?: string };
}
