import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import type { KbArticle } from "../types";
import { Card, CardBody } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import { BookOpen, Search, Plus, ThumbsUp, Eye, Tag, Sparkles, ChevronLeft, ChevronRight } from "lucide-react";
import { timeAgo, cn } from "../lib/utils";

const PAGE_SIZE = 9;

export default function KB() {
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const [tag, setTag] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [page, setPage] = useState(1);

  const { data: articles, isLoading } = useQuery<KbArticle[]>({
    queryKey: ["kb", debouncedSearch, tag],
    queryFn: () =>
      api.get("/kb", { params: { search: debouncedSearch || undefined, tag: tag || undefined } })
        .then((r) => r.data),
  });

  // Extract all unique tags
  const allTags = [...new Set((articles ?? []).flatMap((a) => a.tags))].slice(0, 20);

  const totalPages = Math.ceil((articles?.length ?? 0) / PAGE_SIZE);
  const pagedArticles = useMemo(
    () => (articles ?? []).slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE),
    [articles, page],
  );

  return (
    <div className="p-5 space-y-4 animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-bold text-slate-100">Base de Conocimiento</h1>
          <p className="text-xs text-slate-500 mt-0.5">{articles?.length ?? 0} artículos disponibles</p>
        </div>
        <Button icon={<Plus className="w-4 h-4" />} onClick={() => navigate("/kb/new")}>
          Nuevo artículo
        </Button>
      </div>

      {/* Search */}
      <div className="flex gap-3">
        <div className="flex-1">
          <Input
            placeholder="Buscar por título, contenido, error..."
            value={search}
            icon={<Search className="w-3.5 h-3.5" />}
            onChange={(e) => {
              setSearch(e.target.value);
              clearTimeout((window as any)._kbTimeout);
              (window as any)._kbTimeout = setTimeout(() => setDebouncedSearch(e.target.value), 300);
            }}
          />
        </div>
      </div>

      {/* Tag filter */}
      {allTags.length > 0 && (
        <div className="flex items-center gap-2 flex-wrap">
          <Tag className="w-3.5 h-3.5 text-slate-500" />
          <button
            onClick={() => setTag("")}
            className={cn(
              "px-2.5 py-0.5 rounded-full text-xs border transition-colors",
              !tag ? "bg-accent/10 border-accent/30 text-accent" : "border-ops-600 text-slate-500 hover:text-slate-300",
            )}
          >
            Todos
          </button>
          {allTags.map((t) => (
            <button
              key={t}
              onClick={() => setTag(t === tag ? "" : t)}
              className={cn(
                "px-2.5 py-0.5 rounded-full text-xs border transition-colors",
                tag === t ? "bg-accent/10 border-accent/30 text-accent" : "border-ops-600 text-slate-500 hover:text-slate-300",
              )}
            >
              {t}
            </button>
          ))}
        </div>
      )}

      {/* Articles grid + pagination */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-36 bg-ops-800 rounded-lg border border-ops-600 animate-pulse" />
          ))}
        </div>
      ) : (articles?.length ?? 0) === 0 ? (
        <div className="py-16 text-center">
          <BookOpen className="w-10 h-10 mx-auto mb-3 text-slate-700" />
          <p className="text-slate-500 text-sm">No se encontraron artículos</p>
          {search && (
            <p className="text-slate-600 text-xs mt-1">
              Prueba con otros términos de búsqueda
            </p>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {pagedArticles.map((article) => (
            <Card
              key={article.id}
              hover
              onClick={() => navigate(`/kb/${article.id}`)}
              className="flex flex-col"
            >
              <CardBody className="flex-1 p-4 space-y-3">
                {/* Auto-generated badge */}
                {article.autoGenerated && (
                  <div className="flex items-center gap-1 text-xs text-purple-400">
                    <Sparkles className="w-3 h-3" />
                    Auto-generado desde incidencia
                  </div>
                )}

                <div>
                  <h3 className="text-sm font-semibold text-slate-200 line-clamp-2 leading-snug">
                    {article.title}
                  </h3>
                  {article.summary && (
                    <p className="text-xs text-slate-500 mt-1 line-clamp-2">{article.summary}</p>
                  )}
                </div>

                {/* Tags */}
                {article.tags.length > 0 && (
                  <div className="flex flex-wrap gap-1">
                    {article.tags.slice(0, 4).map((t) => (
                      <span key={t} className="px-1.5 py-0.5 bg-ops-700 text-slate-500 text-xs rounded">
                        {t}
                      </span>
                    ))}
                  </div>
                )}

                {/* Meta */}
                <div className="flex items-center justify-between text-xs text-slate-600 pt-1 mt-auto border-t border-ops-700">
                  <div className="flex items-center gap-3">
                    <span className="flex items-center gap-1">
                      <Eye className="w-3 h-3" /> {article.viewCount}
                    </span>
                    <span className="flex items-center gap-1">
                      <ThumbsUp className="w-3 h-3" /> {article.helpful}
                    </span>
                  </div>
                  <span>{timeAgo(article.updatedAt)}</span>
                </div>
              </CardBody>
            </Card>
          ))}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between text-xs text-slate-500 pt-2">
          <span>
            Mostrando {(page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, articles?.length ?? 0)} de {articles?.length ?? 0}
          </span>
          <div className="flex items-center gap-1">
            <button
              disabled={page === 1}
              onClick={() => setPage((p) => p - 1)}
              className="p-1.5 rounded hover:bg-ops-700 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
              <button
                key={p}
                onClick={() => setPage(p)}
                className={cn(
                  "w-7 h-7 rounded text-xs font-medium transition-colors",
                  p === page ? "bg-accent text-white" : "hover:bg-ops-700 text-slate-400",
                )}
              >
                {p}
              </button>
            ))}
            <button
              disabled={page === totalPages}
              onClick={() => setPage((p) => p + 1)}
              className="p-1.5 rounded hover:bg-ops-700 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
