import { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api, apiError } from "../lib/api";
import type { KbArticle } from "../types";
import { Card, CardBody } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Badge } from "../components/ui/Badge";
import {
  ArrowLeft, ThumbsUp, ThumbsDown, Eye, Edit,
  Link as LinkIcon, Sparkles, Clock
} from "lucide-react";
import { formatDate, cn } from "../lib/utils";
import { Breadcrumb } from "../components/ui/Breadcrumb";
import toast from "react-hot-toast";

function renderInline(text: string): React.ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|_[^_]+_|`[^`]+`)/g).map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**"))
      return <strong key={i} className="font-semibold text-slate-100">{part.slice(2, -2)}</strong>;
    if (part.startsWith("_") && part.endsWith("_"))
      return <em key={i} className="italic text-slate-300">{part.slice(1, -1)}</em>;
    if (part.startsWith("`") && part.endsWith("`"))
      return <code key={i} className="px-1 py-0.5 rounded bg-ops-700 text-accent font-mono text-xs">{part.slice(1, -1)}</code>;
    return part;
  });
}

export default function KBArticle() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const qc = useQueryClient();

  const storageKey = `kb_rating_${id}`;
  const [rated, setRated] = useState<"helpful" | "not" | null>(
    () => localStorage.getItem(storageKey) as "helpful" | "not" | null,
  );

  useEffect(() => {
    if (rated) localStorage.setItem(storageKey, rated);
  }, [rated, storageKey]);

  const { data: article, isLoading } = useQuery<KbArticle>({
    queryKey: ["kb-article", id],
    queryFn: () => api.get(`/kb/${id}`).then((r) => r.data),
  });

  const rate = useMutation({
    mutationFn: (helpful: boolean) => api.post(`/kb/${id}/rate`, { helpful }),
    onSuccess: (_, helpful) => {
      setRated(helpful ? "helpful" : "not");
      qc.invalidateQueries({ queryKey: ["kb-article", id] });
    },
    onError: (err) => toast.error(apiError(err)),
  });

  if (isLoading || !article) {
    return (
      <div className="p-5 animate-pulse space-y-4 max-w-3xl">
        <div className="h-6 bg-ops-700 rounded w-64" />
        <div className="h-96 bg-ops-800 rounded-lg border border-ops-600" />
      </div>
    );
  }

  return (
    <div className="p-5 space-y-4 animate-fade-in max-w-3xl">
      {/* Breadcrumb */}
      <Breadcrumb items={[
        { label: "Dashboard", to: "/" },
        { label: "Base de Conocimiento", to: "/kb" },
        { label: article.title },
      ]} />

      {/* Back + actions */}
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" icon={<ArrowLeft className="w-4 h-4" />} onClick={() => navigate("/kb")}>
          Volver
        </Button>
        <div className="flex-1" />
        <Button variant="ghost" size="sm" icon={<Edit className="w-3.5 h-3.5" />} onClick={() => navigate(`/kb/${id}/edit`)}>
          Editar
        </Button>
      </div>

      {/* Article */}
      <Card>
        <CardBody className="p-6 space-y-4">
          {/* Header */}
          <div className="space-y-2">
            {article.autoGenerated && (
              <div className="flex items-center gap-1.5 text-xs text-purple-400">
                <Sparkles className="w-3.5 h-3.5" />
                Generado automáticamente desde incidencia
                {article.sourceIncident && (
                  <Link
                    to={`/incidents/${article.sourceIncident.id}`}
                    className="underline underline-offset-2 hover:text-purple-300"
                  >
                    {article.sourceIncident.title}
                  </Link>
                )}
              </div>
            )}

            <h1 className="text-xl font-bold text-slate-100">{article.title}</h1>

            <div className="flex items-center gap-3 text-xs text-slate-500">
              <span className="flex items-center gap-1"><Eye className="w-3 h-3" /> {article.viewCount} vistas</span>
              <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {formatDate(article.updatedAt)}</span>
              {article.createdByUser && <span>por {article.createdByUser.displayName}</span>}
              {article.system && (
                <span className="flex items-center gap-1">
                  <LinkIcon className="w-3 h-3" /> {article.system.name}
                </span>
              )}
            </div>

            {/* Tags */}
            {article.tags.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {article.tags.map((t) => (
                  <span key={t} className="px-2 py-0.5 bg-ops-700 border border-ops-600 text-slate-400 text-xs rounded">
                    {t}
                  </span>
                ))}
              </div>
            )}
          </div>

          <hr className="border-ops-600" />

          {/* Content — rendered as markdown-like */}
          <div className="prose-ops space-y-1.5 text-sm text-slate-300 leading-relaxed">
            {(() => {
              let inCode = false;
              const codeLines: string[] = [];
              const nodes: React.ReactNode[] = [];
              const lines = article.content.split("\n");
              lines.forEach((line, i) => {
                if (line.startsWith("```")) {
                  if (!inCode) { inCode = true; return; }
                  inCode = false;
                  nodes.push(
                    <pre key={i} className="my-2 p-3 bg-ops-950 rounded-lg border border-ops-700 overflow-x-auto font-mono text-xs text-slate-300 whitespace-pre">
                      {codeLines.join("\n")}
                    </pre>
                  );
                  codeLines.length = 0;
                  return;
                }
                if (inCode) { codeLines.push(line); return; }
                if (line.startsWith("## ")) return nodes.push(<h2 key={i} className="text-base font-semibold text-slate-100 mt-4 mb-1">{renderInline(line.slice(3))}</h2>);
                if (line.startsWith("### ")) return nodes.push(<h3 key={i} className="text-sm font-semibold text-slate-200 mt-3 mb-1">{renderInline(line.slice(4))}</h3>);
                if (line.startsWith("- ")) return nodes.push(<p key={i} className="flex gap-2 text-slate-400"><span className="text-accent flex-shrink-0">•</span><span>{renderInline(line.slice(2))}</span></p>);
                if (!line.trim()) return nodes.push(<div key={i} className="h-2" />);
                nodes.push(<p key={i}>{renderInline(line)}</p>);
              });
              return nodes;
            })()}
          </div>

          <hr className="border-ops-600" />

          {/* Rating */}
          <div className="flex items-center gap-4">
            <span className="text-sm text-slate-500">¿Fue útil este artículo?</span>
            <button
              onClick={() => !rated && rate.mutate(true)}
              disabled={!!rated}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-sm transition-colors",
                rated === "helpful"
                  ? "border-emerald-500/40 text-emerald-400 bg-emerald-500/10"
                  : "border-ops-600 text-slate-400 hover:border-emerald-500/30 hover:text-emerald-400 disabled:cursor-default",
              )}
            >
              <ThumbsUp className="w-3.5 h-3.5" />
              Sí ({article.helpful})
            </button>
            <button
              onClick={() => !rated && rate.mutate(false)}
              disabled={!!rated}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-sm transition-colors",
                rated === "not"
                  ? "border-red-500/40 text-red-400 bg-red-500/10"
                  : "border-ops-600 text-slate-400 hover:border-red-500/30 hover:text-red-400 disabled:cursor-default",
              )}
            >
              <ThumbsDown className="w-3.5 h-3.5" />
              No ({article.notHelpful})
            </button>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
